spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  flyway:
    enabled: false
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-service-test
    producer:
      # Disable for testing
      bootstrap-servers: localhost:9092

logging:
  level:
    com.mercury.orders: DEBUG
    org.hibernate.SQL: DEBUG





